import { readFile, writeFile } from 'node:fs/promises'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

async function main() {
  const root = new URL('../src/check/viewer/', import.meta.url)
  const bundle = await build({
    entryPoints: [fileURLToPath(new URL('browser.ts', root))],
    bundle: true,
    write: false,
    minify: true,
    format: 'iife',
    platform: 'browser',
    target: ['es2022'],
  })
  const css = await readFile(new URL('style.css', root), 'utf8')
  await writeFile(new URL('assets.generated.ts', root), [
    '// Generated by scripts/build-report-viewer.ts. Do not edit.',
    `export const viewerScript = ${JSON.stringify(bundle.outputFiles[0].text)}`,
    `export const viewerCss = ${JSON.stringify(css)}`,
    '',
  ].join('\n'))
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
